# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrynews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sentScore',
            field=models.FloatField(null=True),
        ),
    ]
